version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./approot:/var/www/html

  app:
    build: ./app
    env_file: .environment
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ./approot:/var/www/html

  db:
    build: ./db
    ports:
      - "3306:3306"
    hostname: db
    env_file: .environment
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local
